version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
  etc_no-ip_config:
  etc_wireguard:

services:
  noip:
    image: aanousakis/no-ip:latest
    container_name:  noip_ddns
    environment:
      - USERNAME=${NOIP_USERNAME}
      - PASSWORD=${NOIP_PASSWORD}
      - HOSTNAMES=${NOIP_HOSTNAMES}
    volumes:
      - /etc/localtime:/etc/localtime
      - etc_no-ip_config:/config
    restart: unless-stopped

  wg-easy:
    build:
      context: ./wg-easy-docker
      dockerfile: Dockerfile
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard_vpn
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=$$2a$$12$$WJhkU56RbkKrdPUfZiJRWO.cyWuO.xtRdvyll/mhglesEEVGKW1da
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS} # This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    volumes:
      - etc_wireguard:/etc/wireguard
    #ports:
      #- "51820:51820/udp"
      #- "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      macvlan_network:
        ipv4_address: 100.64.0.6

  pihole:
    build:
      context: ./pihole-unbound
      dockerfile: Dockerfile
    container_name: pihole_dns
    image: mpgirro/pihole-unbound:latest
    hostname: ${PIHOLE_HOSTNAME}
    domainname: ${PIHOLE_DOMAIN_NAME}
    #ports:      
      #- "443:443/tcp"
      #- "53:53/tcp"
      #- "53:53/udp"
      #- "67:67/udp"
      #- "80:80/tcp" #Allows use of different port to access pihole web interface when other docker containers use port 80
      # - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    networks:
      macvlan_network:
        ipv4_address: 100.64.0.5
    cap_add:  #for host and macvlan network
      - NET_ADMIN  #for host and macvlan network
    environment:
      - FTLCONF_LOCAL_IPV4=${PIHOLE_FTLCONF_LOCAL_IPV4}
      - TZ=${PIHOLE_TZ:-UTC}
      - FTLCONF_webserver_api_password=${PIHOLE_WEBPASSWORD}
      - FTLCONF_webserver_interface_theme=default-auto
      - FTLCONF_dns_revServers=${PIHOLE_REV_SERVER:-false},${PIHOLE_REV_SERVER_CIDR},${PIHOLE_REV_SERVER_TARGET},${PIHOLE_REV_SERVER_DOMAIN}
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec=true
      - FTLCONF_dns_listeningMode=single
      #- DHCP_ACTIVE=true
      #- DHCP_START=100.64.0.200
      #- DHCP_END=100.64.0.250
      #- DHCP_ROUTER=100.64.0.1
      #- DHCP_LEASETIME=24
      #- PIHOLE_DOMAIN=home
      #- DHCP_rapid_commit=true
      #- TEMPERATUREUNIT=f
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped

networks:
  macvlan_network:
    external:
      name: mynet
